import { type Models } from 'appwrite';

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types -l ts /home/nathfavour/Documents/code/web3lancer/pay`.
 */

export type Users = Models.Document & {
  userId: string;
  email: string;
  username: string;
  displayName: string;
  profileImage: string | null;
  phoneNumber: string | null;
  kycStatus: string;
  kycLevel: number;
  twoFactorEnabled: boolean;
  isActive: boolean;
  country: string | null;
  timezone: string | null;
  preferredCurrency: string;
  createdAt: string;
  updatedAt: string;
  wallets: Wallets[];
  transactions: Transactions[];
  paymentRequests: PaymentRequests[];
  securityLogs: SecurityLogs[];
  aPiKeys: ApiKeys[];
}

export type Wallets = Models.Document & {
  walletId: string;
  userId: string;
  walletName: string;
  walletType: string;
  blockchain: string;
  publicKey: string;
  encryptedPrivateKey: string | null;
  walletAddress: string;
  derivationPath: string | null;
  isDefault: boolean;
  isActive: boolean;
  balance: number;
  lastSyncAt: string | null;
  createdAt: string;
  users: Users;
  transactions: Transactions[];
  creationMethod: string | null;
}

export type Tokens = Models.Document & {
  tokenId: string;
  symbol: string;
  name: string;
  blockchain: string;
  contractAddress: string | null;
  decimals: number;
  logoUrl: string | null;
  isStablecoin: boolean;
  isActive: boolean;
  marketCap: number;
  currentPrice: number;
  priceChange24h: number;
  lastPriceUpdate: string | null;
  createdAt: string;
  transactions: Transactions[];
}

export type Transactions = Models.Document & {
  transactionId: string;
  txHash: string | null;
  fromUserId: string;
  toUserId: string[] | null;
  fromWalletId: string;
  toWalletId: string | null;
  fromAddress: string;
  toAddress: string;
  tokenId: string;
  amount: string;
  feeAmount: string;
  gasPrice: string | null;
  gasUsed: string | null;
  status: string;
  type: string;
  description: string | null;
  metadata: string | null;
  blockNumber: number | null;
  confirmations: number;
  createdAt: string;
  confirmedAt: string | null;
  users: Users;
  wallets: Wallets;
  tokens: Tokens;
  paymentRequests: PaymentRequests;
}

export type PaymentRequests = Models.Document & {
  requestId: string;
  fromUserId: string;
  toUserId: string | null;
  toEmail: string | null;
  tokenId: string;
  amount: string;
  description: string | null;
  dueDate: string | null;
  status: string;
  paymentTxId: string | null;
  invoiceNumber: string | null;
  metadata: string | null;
  createdAt: string;
  paidAt: string | null;
  users: Users;
  transactions: Transactions;
}

export type ExchangeRates = Models.Document & {
  rateId: string;
  fromCurrency: string;
  toCurrency: string;
  rate: number;
  source: string;
  lastUpdated: string;
  isActive: boolean;
}

export type SecurityLogs = Models.Document & {
  logId: string;
  userId: string;
  action: string;
  ipAddress: string;
  userAgent: string | null;
  location: string | null;
  success: boolean;
  riskScore: number;
  metadata: string | null;
  createdAt: string;
  users: Users;
}

export type ApiKeys = Models.Document & {
  keyId: string;
  userId: string;
  keyName: string;
  publicKey: string;
  hashedSecret: string;
  permissions: string;
  isActive: boolean;
  lastUsed: string | null;
  expiresAt: string | null;
  createdAt: string;
  users: Users;
}

export type VirtualCards = Models.Document & {
  cardId: string;
  userId: string;
  cardNumber: string;
  expiry: string;
  cvv: string;
  cardType: string;
  status: string;
  linkedWalletId: string | null;
  createdAt: string | null;
  updatedAt: string | null;
}

export type VirtualAccounts = Models.Document & {
  accountId: string;
  userId: string;
  accountNumber: string;
  currency: string | null;
  balance: number | null;
  status: string | null;
  linkedWalletId: string | null;
  createdAt: string | null;
  updatedAt: string | null;
}

